// Player Spotlight Data (Home Page)
const spotlightPlayers = [
    [
        "Aaron Judge",
        "Right Field",
        "assets/img/judge_number.jpg",
        "Captain and power hitter, Judge set the AL home run record with 62 in 2022."
    ],
    [
        "Gerrit Cole",
        "Pitcher",
        "assets/img/cole_number.jpg",
        "Ace of the staff, Cole won the 2023 AL Cy Young Award."
    ],
    [
        "Anthony Volpe",
        "Shortstop",
        "assets/img/volpe_number.jpg",
        "Young star and Gold Glove winner, Volpe is the future of the infield."
    ]
];

// Generate Player Spotlight (Home Page)
function loadSpotlight() {
    const spotlightDiv = document.getElementById("spotlight");
    if (spotlightDiv) {
        let html = "";
        for (let i = 0; i < spotlightPlayers.length; i++) {
            const [name, position, imgSrc, bio] = spotlightPlayers[i];
            html += `
                <div class="col-md-4 col-12">
                    <div class="jersey-card">
                        <img src="${imgSrc}" alt="Jersey number of ${name} generated by Grok 3">
                        <div class="jersey-overlay">
                            <h3>${name}</h3>
                            <p><strong>${position}</strong><br>${bio}</p>
                        </div>
                    </div>
                </div>
            `;
        }
        spotlightDiv.innerHTML = html;

        // Mobile tap-to-reveal
        const cards = document.querySelectorAll(".jersey-card");
        cards.forEach(card => {
            card.addEventListener("click", function () {
                if (window.innerWidth <= 768) {
                    card.classList.toggle("active");
                }
            });
        });
    }
}

// Roster Page: Player Cards
const rosterPlayers = [
    ["Aaron Judge", "Right Field", "assets/img/judge.jpg"],
    ["Gerrit Cole", "Pitcher", "assets/img/cole.jpg"],
    ["Anthony Volpe", "Shortstop", "assets/img/volpe.jpg"]
];

function loadRoster() {
    const rosterDiv = document.getElementById("roster");
    if (rosterDiv) {
        let html = "";
        for (let i = 0; i < rosterPlayers.length; i++) {
            const [name, position, imgSrc] = rosterPlayers[i];
            html += `
                <div class="col-md-4 col-12 mb-4">
                    <div class="card">
                        <img src="${imgSrc}" class="card-img-top" alt="Image of ${name} generated by Grok 3">
                        <div class="card-body">
                            <h5 class="card-title">${name}</h5>
                            <p class="card-text">${position}</p>
                        </div>
                    </div>
                </div>
            `;
        }
        rosterDiv.innerHTML = html;
    }
}

// Roster Page: Favorite Player Form
function handleFavoriteForm() {
    const form = document.getElementById("favoriteForm");
    const message = document.getElementById("formMessage");
    if (form) {
        form.addEventListener("submit", function (e) {
            e.preventDefault();
            const playerName = document.getElementById("playerName").value.trim();
            if (playerName.length > 2) {
                message.textContent = `Great choice! ${playerName} is a true Yankee!`;
                message.style.color = "green";
            } else {
                message.textContent = "Please enter a valid player name.";
                message.style.color = "red";
            }
            form.reset();
        });
    }
}

// History Page: Timeline
const milestones = [
    ["1923", "First World Series", "The Yankees won their first championship.", "assets/img/1923.jpg"],
    ["1961", "Mantle & Maris", "Roger Maris broke Babe Ruth's home run record.", "assets/img/1961.jpg"],
    ["2009", "27th Title", "Yankees defeated the Phillies for their 27th World Series.", "assets/img/2009.jpg"]
];

function loadTimeline() {
    const buttons = document.querySelectorAll("#timeline button");
    const milestoneDiv = document.getElementById("milestone");
    const milestoneImg = document.getElementById("milestoneImg");
    const milestoneTitle = document.getElementById("milestoneTitle");
    const milestoneText = document.getElementById("milestoneText");

    if (buttons.length > 0) {
        buttons.forEach(button => {
            button.addEventListener("click", function () {
                const year = this.getAttribute("data-year");
                for (let i = 0; i < milestones.length; i++) {
                    if (milestones[i][0] === year) {
                        const [_, title, text, imgSrc] = milestones[i];
                        milestoneImg.src = imgSrc;
                        milestoneImg.alt = `Milestone image for ${year} generated by Grok 3`;
                        milestoneTitle.textContent = title;
                        milestoneText.textContent = text;
                        milestoneDiv.classList.add("show");
                        break;
                    }
                }
            });
        });
    }
}

// Initialize Page
document.addEventListener("DOMContentLoaded", function () {
    loadSpotlight();
    loadRoster();
    handleFavoriteForm();
    loadTimeline();
});